[package]
name = "tracing-elastic-apm"
version = "1.0.0"
authors = ["Kamil Rojewski <kamil.rojewski@gmail.com>"]
edition = "2018"
description = "Elasting APM intake API tracing layer."
documentation = "https://docs.rs/tracing-elastic-apm"
homepage = "https://github.com/krojew/tracing-elastic-apm"
repository = "https://github.com/krojew/tracing-elastic-apm"
readme = "./README.md"
keywords = ["tracing", "elastic", "apm", "telemetry"]
license = "MIT/Apache-2.0"

[dependencies]
base64 = "0.13"
fxhash = "0.2"
rand = "0.7"
reqwest = "0.10"
serde = "1.0"
serde_json = "1.0"
tokio = { version = "0.3", features = ["rt"] }
tokio-compat-02 = "0.1"
tracing = "0.1"
tracing-subscriber = "0.2"
version = "3.0"
